dist: focal
sudo: false
language: c
#env:
#  matrix:
#    - VALGRIND=On SANITIZERS=Off
#    - VALGRIND=Off SANITIZERS=Off
#    - VALGRIND=Off SANITIZERS=On
compiler:
  - gcc
addons:
  apt:
    packages:
      - libmicrohttpd-dev
      - libhiredis-dev
      - libgcrypt-dev
      - dieharder
script:
  - cd src
  - ./compile.sh
  - ./compile_chaosstorage.sh
