dist: focal
sudo: false
language: c
compiler:
  - gcc
addons:
  apt:
    packages:
      - libmicrohttpd-dev
      - libhiredis-dev
      - libgcrypt-dev
      - dieharder
script:
  - cd src
  - ./compile.sh
  - ./compile_chaosservice.sh
